[versions]
androidx-annotation = "1.9.1"
commons-compress = "1.28.0"
desugar-jdk-libs-nio = "2.1.5"
ecj = "3.42.0"
foojay-resolver-convention = "1.0.0"
kotlin = "2.3.21"
r8 = "8.13.17"
xz = "1.12"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
apache-commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
desugar-jdk-libs-nio = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "desugar-jdk-libs-nio" }
desugar-jdk-libs-configuration-nio = { module = "com.android.tools:desugar_jdk_libs_configuration_nio", version.ref = "desugar-jdk-libs-nio" }
ecj = { module = "org.eclipse.jdt:ecj", version.ref = "ecj" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
r8 = { module = "com.android.tools:r8", version.ref = "r8" }
tukaani-xz = { module = "org.tukaani:xz", version.ref = "xz" }
